path: data/processed/level1_sequence3
train: images/train
val: images/val
test: images/test
masks_dir: masks
nc: 7
names:
- drivable
- non-drivable
- living-thing
- vehicles
- barrier-structures
- construction-vegetation
- sky
