path: data/processed/level1_official
train: images/train
val: images/val
masks_dir: masks
nc: 7
names:
- drivable
- non-drivable
- living-thing
- vehicles
- barrier-structures
- construction-vegetation
- sky
